version: '3.8'
services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network1
  db:
    image: postgres:14
    networks:
      - network2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
networks:
  network1:
    name: bridge1
  network2:
    name: bridge2